# Generated by Django 3.2 on 2021-07-07 02:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('precontent', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='postCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('blue', 'blue'), ('indigo', 'indigo'), ('purple', 'purple'), ('pink', 'pink'), ('danger', 'danger'), ('orange', 'orange'), ('brown', 'brown'), ('warning', 'warning'), ('success', 'success'), ('info', 'info'), ('cyan', 'cyan')], default='blue', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PostPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('image_name', models.CharField(blank=True, default='', max_length=55, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='blog.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.postcategory'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('city', models.CharField(max_length=30)),
                ('region', models.CharField(choices=[('XV', 'Arica y Parinacota'), ('I', 'Tarapacá'), ('II', 'Antofagasta'), ('III', 'Atacama'), ('IV', 'Coquimbo'), ('V', 'Valparaíso'), ('RM', 'Santiago'), ('VI', 'Libertador General Bernardo Ohiggins'), ('VII', 'Maule'), ('XVI', 'Ñuble'), ('VIII', 'Biobío'), ('IX', 'La Araucanía'), ('XIV', 'Los Ríos'), ('X', 'Los lagos'), ('XI', 'Aysen'), ('XII', 'Magallanes y Antártica')], max_length=40)),
                ('genero', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('No Binario', 'No Binario'), ('Otro', 'Otro')], default='Selecciona uno', max_length=20)),
                ('is_fotografo', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=50, null=True)),
                ('portafolio', models.URLField()),
                ('rutaImagen', models.FileField(null=True, upload_to='')),
                ('idioma', multiselectfield.db.fields.MultiSelectField(choices=[('en', 'Inglés'), ('de', 'Alemán'), ('fr', 'Francés'), ('pt', 'Portugués'), ('ru', 'Ruso')], max_length=14, null=True)),
                ('categoriasEspecialidad', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Matrimonio'), (2, 'Fiesta'), (3, 'Eventos Musicales'), (4, 'Eventos Deportivos'), (5, 'Mascota'), (6, 'Fotografía de producto'), (7, 'Fotografía aérea')], max_length=13, null=True)),
                ('disponibilidad', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Full Time'), (2, 'Part Time'), (3, 'Casual'), (4, 'Fin de Semanas'), (8, 'Festivos'), (5, 'Mañanas'), (6, 'Tardes'), (7, 'Noches')], max_length=15, null=True)),
                ('fotografo', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
